import Head from 'next/head';
import Colors from '../components/colors/Colors';

export default function Home() {
  return (
    <>
      <Head>
        <title>Color Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Colors />
    </>
  );
}
